apiVersion: v1
kind: ReplicationController
metadata:
  name: portal
  labels:
    name: portal
spec:
  replicas: 2
  selector:
    name: portal
  template:
    metadata:
      labels:
        name: portal
    spec:
      containers:
      - name: portal
        image: devopsopen/docker-pipeline-portal:latest
        ports:
        - containerPort: 3000
