apiVersion: v1
kind: ReplicationController
metadata:
  name: wekan
  labels:
    name: wekan
spec:
  replicas: 2
  selector:
    name: wekan
  template:
    metadata:
      labels:
        name: wekan
    spec:
      containers:
      - name: wekan
        image: devopsopen/docker-ca-wekan:lastest
        ports:
        - containerPort: 80
